version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    build: ./app
    container_name: app
    command: npm start
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    