# Generated by Django 4.0.6 on 2022-07-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory_subproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'verbose_name': 'Subproduct', 'verbose_name_plural': 'Subproducts'},
        ),
    ]
