# Generated by Django 4.0.6 on 2022-07-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_subcategory_options_alter_subproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subproduct')),
            ],
            options={
                'verbose_name': 'Selected Subproduct',
                'verbose_name_plural': 'Selected Subproducts',
            },
        ),
    ]
